import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { requireUser } from "../middleware/auth.js";
import { recalculateTaskRecommendation, recalculateUserRecommendations } from "../services/recommendations/recommendationService.js";
import { generateNotificationPreviews } from "../services/notifications/notificationService.js";

export const dataRouter = Router(); dataRouter.use(requireUser);
dataRouter.get("/courses", async (req, res, next) => { try { res.json({ courses: await prisma.course.findMany({ where: { userId: req.userId, providerId: { not: "mock_canvas" } }, include: { _count: { select: { tasks: { where: { removedAt: null, providerId: { not: "mock_canvas" } } } } } }, orderBy: { code: "asc" } }) }); } catch (error) { next(error); } });
dataRouter.patch("/courses/:id", async (req, res, next) => { try { const body = z.object({ difficulty: z.enum(["easy", "normal", "hard"]).optional(), active: z.boolean().optional(), currentGradePercent: z.number().min(0).max(100).nullable().optional(), targetGradePercent: z.number().min(0).max(100).nullable().optional(), gradeGoalLabel: z.enum(["maintain_a", "raise_grade", "pass_safely", "custom"]).nullable().optional(), courseImportance: z.enum(["normal", "important", "critical"]).optional(), gradeDataSource: z.literal("manual").optional() }).parse(req.body); const course = await prisma.course.findFirst({ where: { id: req.params.id, userId: req.userId, providerId: { not: "mock_canvas" } } }); if (!course) return res.status(404).json({ error: "Course not found." }); const updated = await prisma.course.update({ where: { id: course.id }, data: body }); if ("currentGradePercent" in body || "targetGradePercent" in body || "courseImportance" in body) { await recalculateUserRecommendations(req.userId!); await generateNotificationPreviews(req.userId!); } res.json({ course: updated }); } catch (error) { next(error); } });
dataRouter.get("/tasks", async (req, res, next) => { try { const q = typeof req.query.q === "string" ? req.query.q : undefined; const where = { userId: req.userId!, providerId: { not: "mock_canvas" }, removedAt: null, ...(typeof req.query.courseId === "string" ? { courseId: req.query.courseId } : {}), ...(typeof req.query.type === "string" ? { type: req.query.type as never } : {}), ...(typeof req.query.status === "string" ? { status: req.query.status as never } : {}), ...(typeof req.query.dueBefore === "string" ? { dueAt: { lte: new Date(req.query.dueBefore) } } : {}), ...(typeof req.query.dueAfter === "string" ? { dueAt: { gte: new Date(req.query.dueAfter) } } : {}), ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" as const } }, { course: { code: { contains: q, mode: "insensitive" as const } } }] } : {}) }; res.json({ tasks: await prisma.academicTask.findMany({ where, include: { course: true, recommendations: { where: { userId: req.userId }, take: 1, orderBy: { updatedAt: "desc" } } }, orderBy: { dueAt: "asc" } }) }); } catch (error) { next(error); } });
dataRouter.get("/sync/changes", async (req, res, next) => { try { const events = await prisma.taskEvent.findMany({ where: { userId: req.userId, task: { providerId: { not: "mock_canvas" } }, eventType: { in: ["created", "due_date_changed", "points_changed", "removed"] } }, include: { task: { include: { course: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); res.json({ events }); } catch (error) { next(error); } });
dataRouter.get("/me", async (req, res, next) => { try { const user = await prisma.user.findUnique({ where: { id: req.userId }, include: { settings: true } }); res.json({ user }); } catch (error) { next(error); } });
dataRouter.patch("/me/settings", async (req, res, next) => { try { const settings = z.object({ defaultReminderHour: z.number().int().min(0).max(23).optional(), defaultReminderMinute: z.number().int().min(0).max(59).optional(), reminderStyle: z.enum(["conservative", "balanced", "aggressive"]).optional(), defaultChannel: z.enum(["email", "in_app", "calendar"]).optional(), weekendRemindersEnabled: z.boolean().optional(), digestEnabled: z.boolean().optional(), emailEnabled: z.boolean().optional() }).parse(req.body); const updated = await prisma.userSettings.update({ where: { userId: req.userId }, data: settings }); await prisma.notification.deleteMany({ where: { userId: req.userId, status: "preview" } }); await generateNotificationPreviews(req.userId!); res.json({ settings: updated }); } catch (error) { next(error); } });
dataRouter.post("/onboarding/complete", async (req, res, next) => { try { const body = z.object({ schoolName: z.string().min(1).max(120), timezone: z.string().min(1), reminderStyle: z.enum(["conservative", "balanced", "aggressive"]), defaultReminderHour: z.number().int().min(0).max(23), defaultReminderMinute: z.number().int().min(0).max(59).default(0) }).parse(req.body); await prisma.user.update({ where: { id: req.userId }, data: { schoolName: body.schoolName, timezone: body.timezone } }); const settings = await prisma.userSettings.update({ where: { userId: req.userId }, data: { reminderStyle: body.reminderStyle, defaultReminderHour: body.defaultReminderHour, defaultReminderMinute: body.defaultReminderMinute, onboardingCompleted: true } }); res.json({ settings }); } catch (error) { next(error); } });
dataRouter.get("/tasks/:id", async (req, res, next) => { try { const task = await prisma.academicTask.findFirst({ where: { id: req.params.id, userId: req.userId, providerId: { not: "mock_canvas" } }, include: { course: true, recommendations: { orderBy: { updatedAt: "desc" } }, events: { orderBy: { createdAt: "desc" } }, notifications: { orderBy: { createdAt: "desc" } } } }); if (!task) return res.status(404).json({ error: "Task not found." }); res.json({ task }); } catch (error) { next(error); } });
dataRouter.patch("/tasks/:id/status", async (req, res, next) => { try { const body = z.object({ status: z.enum(["upcoming", "start_now", "in_progress", "done", "overdue"]) }).parse(req.body); const result = await prisma.academicTask.updateMany({ where: { id: req.params.id, userId: req.userId, providerId: { not: "mock_canvas" } }, data: body }); res.json(result); } catch (error) { next(error); } });
dataRouter.patch("/tasks/:id/enrichment", async (req, res, next) => { try { const body = z.object({ type: z.enum(["assignment", "quiz", "exam", "project", "reading", "discussion", "lab", "other"]).optional(), difficulty: z.enum(["low", "medium", "high"]).optional(), estimatedMinutes: z.number().int().positive().max(10080).nullable().optional(), pointsPossible: z.number().nonnegative().nullable().optional(), status: z.enum(["upcoming", "in_progress", "done"]).optional() }).parse(req.body); const task = await prisma.academicTask.findFirst({ where: { id: req.params.id, userId: req.userId, providerId: { in: ["ical_feed", "manual_import"] } } }); if (!task) return res.status(404).json({ error: "Only imported coursework can be enriched here." }); await prisma.academicTask.update({ where: { id: task.id }, data: body }); const recommendation = await recalculateTaskRecommendation(req.userId!, task.id); await generateNotificationPreviews(req.userId!); res.json({ taskId: task.id, recommendation }); } catch (error) { next(error); } });
dataRouter.get("/insights", async (req, res, next) => { try { const realTask = { userId: req.userId!, providerId: { not: "mock_canvas" }, removedAt: null }; const [upcoming, startNow, dueThisWeek, preferences] = await Promise.all([prisma.academicTask.count({ where: { ...realTask, dueAt: { gt: new Date() } } }), prisma.academicTask.count({ where: { ...realTask, status: "start_now" } }), prisma.academicTask.count({ where: { ...realTask, dueAt: { gte: new Date(), lte: new Date(Date.now() + 7 * 86_400_000) } } }), prisma.learningPreference.findMany({ where: { userId: req.userId } })]); res.json({ upcoming, startNow, dueThisWeek, learningPreferences: preferences }); } catch (error) { next(error); } });
