import { Router } from "express";
import { z } from "zod";
import { prisma } from "../lib/prisma.js";
import { requireUser } from "../middleware/auth.js";

export const dataRouter = Router(); dataRouter.use(requireUser);
dataRouter.get("/courses", async (req, res, next) => { try { res.json({ courses: await prisma.course.findMany({ where: { userId: req.userId }, include: { _count: { select: { tasks: { where: { removedAt: null } } } } }, orderBy: { code: "asc" } }) }); } catch (error) { next(error); } });
dataRouter.patch("/courses/:id", async (req, res, next) => { try { const body = z.object({ difficulty: z.enum(["easy", "normal", "hard"]).optional(), active: z.boolean().optional() }).parse(req.body); const course = await prisma.course.updateMany({ where: { id: req.params.id, userId: req.userId }, data: body }); res.json(course); } catch (error) { next(error); } });
dataRouter.get("/tasks", async (req, res, next) => { try { const q = typeof req.query.q === "string" ? req.query.q : undefined; const where = { userId: req.userId!, removedAt: null, ...(typeof req.query.courseId === "string" ? { courseId: req.query.courseId } : {}), ...(typeof req.query.type === "string" ? { type: req.query.type as never } : {}), ...(typeof req.query.status === "string" ? { status: req.query.status as never } : {}), ...(typeof req.query.dueBefore === "string" ? { dueAt: { lte: new Date(req.query.dueBefore) } } : {}), ...(typeof req.query.dueAfter === "string" ? { dueAt: { gte: new Date(req.query.dueAfter) } } : {}), ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" as const } }, { course: { code: { contains: q, mode: "insensitive" as const } } }] } : {}) }; res.json({ tasks: await prisma.academicTask.findMany({ where, include: { course: true, recommendations: { where: { userId: req.userId }, take: 1, orderBy: { updatedAt: "desc" } } }, orderBy: { dueAt: "asc" } }) }); } catch (error) { next(error); } });
dataRouter.get("/sync/changes", async (req, res, next) => { try { const events = await prisma.taskEvent.findMany({ where: { userId: req.userId, eventType: { in: ["created", "due_date_changed", "points_changed", "removed"] } }, include: { task: { include: { course: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); res.json({ events }); } catch (error) { next(error); } });
dataRouter.get("/me", async (req, res, next) => { try { const user = await prisma.user.findUnique({ where: { id: req.userId }, include: { settings: true } }); res.json({ user }); } catch (error) { next(error); } });
dataRouter.patch("/me/settings", async (req, res, next) => { try { const settings = z.object({ defaultReminderHour: z.number().int().min(0).max(23).optional(), reminderStyle: z.enum(["conservative", "balanced", "aggressive"]).optional(), defaultChannel: z.enum(["email", "in_app", "calendar"]).optional(), weekendRemindersEnabled: z.boolean().optional(), digestEnabled: z.boolean().optional(), emailEnabled: z.boolean().optional() }).parse(req.body); res.json({ settings: await prisma.userSettings.update({ where: { userId: req.userId }, data: settings }) }); } catch (error) { next(error); } });
dataRouter.post("/onboarding/complete", async (req, res, next) => { try { const body = z.object({ schoolName: z.string().min(1).max(120), timezone: z.string().min(1), reminderStyle: z.enum(["conservative", "balanced", "aggressive"]), defaultReminderHour: z.number().int().min(0).max(23) }).parse(req.body); await prisma.user.update({ where: { id: req.userId }, data: { schoolName: body.schoolName, timezone: body.timezone } }); const settings = await prisma.userSettings.update({ where: { userId: req.userId }, data: { reminderStyle: body.reminderStyle, defaultReminderHour: body.defaultReminderHour, onboardingCompleted: true } }); res.json({ settings }); } catch (error) { next(error); } });
dataRouter.get("/tasks/:id", async (req, res, next) => { try { const task = await prisma.academicTask.findFirst({ where: { id: req.params.id, userId: req.userId }, include: { course: true, recommendations: { orderBy: { updatedAt: "desc" } }, events: { orderBy: { createdAt: "desc" } }, notifications: { orderBy: { createdAt: "desc" } } } }); if (!task) return res.status(404).json({ error: "Task not found." }); res.json({ task }); } catch (error) { next(error); } });
dataRouter.patch("/tasks/:id/status", async (req, res, next) => { try { const body = z.object({ status: z.enum(["upcoming", "start_now", "in_progress", "done", "overdue"]) }).parse(req.body); const result = await prisma.academicTask.updateMany({ where: { id: req.params.id, userId: req.userId }, data: body }); res.json(result); } catch (error) { next(error); } });
dataRouter.get("/insights", async (req, res, next) => { try { const [upcoming, startNow, dueThisWeek, preferences] = await Promise.all([prisma.academicTask.count({ where: { userId: req.userId, removedAt: null, dueAt: { gt: new Date() } } }), prisma.academicTask.count({ where: { userId: req.userId, status: "start_now", removedAt: null } }), prisma.academicTask.count({ where: { userId: req.userId, removedAt: null, dueAt: { gte: new Date(), lte: new Date(Date.now() + 7 * 86_400_000) } } }), prisma.learningPreference.findMany({ where: { userId: req.userId } })]); res.json({ upcoming, startNow, dueThisWeek, learningPreferences: preferences }); } catch (error) { next(error); } });
