import { Router } from "express";
import { prisma } from "../lib/prisma.js";
import { z } from "zod";
import { requireUser } from "../middleware/auth.js";
import { generateNotificationPreviews } from "../services/notifications/notificationService.js";

export const notificationRouter = Router(); notificationRouter.use(requireUser);
const recipientSchema = z.object({ email: z.string().email(), label: z.string().min(1).max(80), relationship: z.enum(["self", "parent_guardian", "other"]), enabled: z.boolean().default(true), startWindowEnabled: z.boolean().default(true), dueSoonEnabled: z.boolean().default(true), deadlineChangedEnabled: z.boolean().default(true), weeklyDigestEnabled: z.boolean().default(true) });
notificationRouter.get("/notifications", async (req, res, next) => { try { res.json({ notifications: await prisma.notification.findMany({ where: { userId: req.userId }, include: { task: { include: { course: true } }, recipient: true }, orderBy: { createdAt: "desc" } }) }); } catch (error) { next(error); } });
notificationRouter.get("/reminder-recipients", async (req, res, next) => { try { const user = await prisma.user.findUnique({ where: { id: req.userId }, select: { email: true, name: true } }); if (!user) return res.status(404).json({ error: "User not found." }); const primary = await prisma.reminderRecipient.upsert({ where: { userId_email: { userId: req.userId!, email: user.email } }, create: { userId: req.userId!, email: user.email, label: user.name ?? "My primary email", relationship: "self", demoVerified: true }, update: {} }); const recipients = await prisma.reminderRecipient.findMany({ where: { userId: req.userId }, orderBy: [{ relationship: "asc" }, { createdAt: "asc" }] }); res.json({ primaryRecipientId: primary.id, recipients }); } catch (error) { next(error); } });
notificationRouter.post("/reminder-recipients", async (req, res, next) => { try { const body = recipientSchema.parse(req.body); const recipient = await prisma.reminderRecipient.create({ data: { ...body, userId: req.userId! } }); res.status(201).json({ recipient }); } catch (error) { next(error); } });
notificationRouter.patch("/reminder-recipients/:id", async (req, res, next) => { try { const body = recipientSchema.partial().extend({ demoVerified: z.boolean().optional() }).parse(req.body); const recipient = await prisma.reminderRecipient.updateMany({ where: { id: req.params.id, userId: req.userId }, data: body }); res.json(recipient); } catch (error) { next(error); } });
notificationRouter.post("/reminder-recipients/:id/verify-demo", async (req, res, next) => { try { const recipient = await prisma.reminderRecipient.updateMany({ where: { id: req.params.id, userId: req.userId }, data: { demoVerified: true } }); res.json(recipient); } catch (error) { next(error); } });
notificationRouter.delete("/reminder-recipients/:id", async (req, res, next) => { try { const recipient = await prisma.reminderRecipient.deleteMany({ where: { id: req.params.id, userId: req.userId, relationship: { not: "self" } } }); res.json(recipient); } catch (error) { next(error); } });
notificationRouter.post("/notifications/generate", async (req, res, next) => { try { res.json({ created: await generateNotificationPreviews(req.userId!) }); } catch (error) { next(error); } });
notificationRouter.patch("/notifications/:id/read", async (req, res, next) => { try { const notification = await prisma.notification.updateMany({ where: { id: req.params.id, userId: req.userId }, data: { status: "sent", sentAt: new Date() } }); res.json(notification); } catch (error) { next(error); } });
