CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "ReminderStyle" AS ENUM ('conservative', 'balanced', 'aggressive');
CREATE TYPE "NotificationChannel" AS ENUM ('email', 'in_app', 'calendar');
CREATE TYPE "CourseDifficulty" AS ENUM ('easy', 'normal', 'hard');
CREATE TYPE "TaskType" AS ENUM ('assignment', 'quiz', 'exam', 'project', 'reading', 'discussion', 'lab', 'other');
CREATE TYPE "TaskDifficulty" AS ENUM ('low', 'medium', 'high');
CREATE TYPE "TaskStatus" AS ENUM ('upcoming', 'start_now', 'in_progress', 'done', 'overdue');
CREATE TYPE "TaskEventType" AS ENUM ('created', 'updated', 'due_date_changed', 'title_changed', 'points_changed', 'removed', 'completed', 'recommendation_changed');
CREATE TYPE "ProviderKind" AS ENUM ('mock_canvas', 'canvas_ical', 'canvas_oauth_future');
CREATE TYPE "ConnectionStatus" AS ENUM ('connected', 'disconnected', 'demo', 'error');
CREATE TYPE "SyncStatus" AS ENUM ('started', 'success', 'failed');
CREATE TYPE "NotificationType" AS ENUM ('start_recommendation', 'due_soon', 'deadline_changed', 'overdue', 'digest', 'feedback_request');
CREATE TYPE "NotificationStatus" AS ENUM ('scheduled', 'sent', 'failed', 'skipped', 'preview');
CREATE TYPE "FeedbackType" AS ENUM ('too_early', 'about_right', 'too_late', 'need_more_time', 'need_less_time', 'not_relevant');
CREATE TYPE "LearningScope" AS ENUM ('global', 'course', 'task_type', 'course_task_type');

CREATE TABLE "User" ("id" TEXT NOT NULL, "authProviderId" TEXT, "email" TEXT NOT NULL, "name" TEXT, "schoolName" TEXT, "timezone" TEXT NOT NULL DEFAULT 'America/New_York', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserSettings" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "defaultReminderHour" INTEGER NOT NULL DEFAULT 9, "reminderStyle" "ReminderStyle" NOT NULL DEFAULT 'balanced', "defaultChannel" "NotificationChannel" NOT NULL DEFAULT 'in_app', "weekendRemindersEnabled" BOOLEAN NOT NULL DEFAULT true, "digestEnabled" BOOLEAN NOT NULL DEFAULT true, "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "UserSettings_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Course" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "providerId" TEXT NOT NULL, "externalId" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "instructorName" TEXT, "color" TEXT NOT NULL DEFAULT '#5EEAD4', "term" TEXT, "difficulty" "CourseDifficulty" NOT NULL DEFAULT 'normal', "active" BOOLEAN NOT NULL DEFAULT true, "lastSyncedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Course_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AcademicTask" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "courseId" TEXT NOT NULL, "providerId" TEXT NOT NULL, "externalId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT, "type" "TaskType" NOT NULL DEFAULT 'other', "dueAt" TIMESTAMP(3) NOT NULL, "availableAt" TIMESTAMP(3), "pointsPossible" DOUBLE PRECISION, "estimatedMinutes" INTEGER, "difficulty" "TaskDifficulty" NOT NULL DEFAULT 'medium', "status" "TaskStatus" NOT NULL DEFAULT 'upcoming', "sourceUrl" TEXT, "rawSource" JSONB, "removedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AcademicTask_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TaskEvent" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "eventType" "TaskEventType" NOT NULL, "previousValue" JSONB, "newValue" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TaskEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProviderConnection" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "provider" "ProviderKind" NOT NULL, "displayName" TEXT NOT NULL, "status" "ConnectionStatus" NOT NULL DEFAULT 'demo', "config" JSONB, "lastSyncAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProviderConnection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SyncRun" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "providerConnectionId" TEXT NOT NULL, "status" "SyncStatus" NOT NULL DEFAULT 'started', "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "finishedAt" TIMESTAMP(3), "coursesFound" INTEGER NOT NULL DEFAULT 0, "tasksFound" INTEGER NOT NULL DEFAULT 0, "tasksCreated" INTEGER NOT NULL DEFAULT 0, "tasksUpdated" INTEGER NOT NULL DEFAULT 0, "tasksRemoved" INTEGER NOT NULL DEFAULT 0, "errorMessage" TEXT, "metadata" JSONB, CONSTRAINT "SyncRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Recommendation" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "taskId" TEXT NOT NULL, "recommendedStartAt" TIMESTAMP(3) NOT NULL, "priorityScore" DOUBLE PRECISION NOT NULL, "confidenceScore" DOUBLE PRECISION NOT NULL, "leadTimeDays" DOUBLE PRECISION NOT NULL, "estimatedEffortMinutes" INTEGER, "explanation" TEXT NOT NULL, "factors" JSONB, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Recommendation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "taskId" TEXT, "recommendationId" TEXT, "type" "NotificationType" NOT NULL, "channel" "NotificationChannel" NOT NULL, "status" "NotificationStatus" NOT NULL DEFAULT 'preview', "scheduledFor" TIMESTAMP(3), "sentAt" TIMESTAMP(3), "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "providerMessageId" TEXT, "failureReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Feedback" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "taskId" TEXT, "recommendationId" TEXT, "notificationId" TEXT, "feedbackType" "FeedbackType" NOT NULL, "comment" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Feedback_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LearningPreference" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "scopeType" "LearningScope" NOT NULL, "courseId" TEXT, "taskType" "TaskType", "leadTimeAdjustmentDays" DOUBLE PRECISION NOT NULL DEFAULT 0, "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0, "sampleSize" INTEGER NOT NULL DEFAULT 0, "lastUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "LearningPreference_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CalendarToken" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "token" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3), CONSTRAINT "CalendarToken_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_authProviderId_key" ON "User"("authProviderId");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "UserSettings_userId_key" ON "UserSettings"("userId");
CREATE INDEX "Course_userId_active_idx" ON "Course"("userId", "active");
CREATE UNIQUE INDEX "Course_userId_providerId_externalId_key" ON "Course"("userId", "providerId", "externalId");
CREATE INDEX "AcademicTask_userId_dueAt_idx" ON "AcademicTask"("userId", "dueAt");
CREATE INDEX "AcademicTask_courseId_dueAt_idx" ON "AcademicTask"("courseId", "dueAt");
CREATE UNIQUE INDEX "AcademicTask_userId_providerId_externalId_key" ON "AcademicTask"("userId", "providerId", "externalId");
CREATE INDEX "TaskEvent_userId_createdAt_idx" ON "TaskEvent"("userId", "createdAt");
CREATE INDEX "TaskEvent_taskId_createdAt_idx" ON "TaskEvent"("taskId", "createdAt");
CREATE UNIQUE INDEX "ProviderConnection_userId_provider_key" ON "ProviderConnection"("userId", "provider");
CREATE INDEX "SyncRun_userId_startedAt_idx" ON "SyncRun"("userId", "startedAt");
CREATE INDEX "Recommendation_userId_taskId_idx" ON "Recommendation"("userId", "taskId");
CREATE INDEX "Notification_userId_status_idx" ON "Notification"("userId", "status");
CREATE INDEX "Feedback_userId_createdAt_idx" ON "Feedback"("userId", "createdAt");
CREATE INDEX "LearningPreference_userId_scopeType_idx" ON "LearningPreference"("userId", "scopeType");
CREATE UNIQUE INDEX "CalendarToken_token_key" ON "CalendarToken"("token");

ALTER TABLE "UserSettings" ADD CONSTRAINT "UserSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Course" ADD CONSTRAINT "Course_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AcademicTask" ADD CONSTRAINT "AcademicTask_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AcademicTask" ADD CONSTRAINT "AcademicTask_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaskEvent" ADD CONSTRAINT "TaskEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaskEvent" ADD CONSTRAINT "TaskEvent_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "AcademicTask"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProviderConnection" ADD CONSTRAINT "ProviderConnection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SyncRun" ADD CONSTRAINT "SyncRun_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SyncRun" ADD CONSTRAINT "SyncRun_providerConnectionId_fkey" FOREIGN KEY ("providerConnectionId") REFERENCES "ProviderConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Recommendation" ADD CONSTRAINT "Recommendation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Recommendation" ADD CONSTRAINT "Recommendation_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "AcademicTask"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "AcademicTask"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_recommendationId_fkey" FOREIGN KEY ("recommendationId") REFERENCES "Recommendation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "AcademicTask"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_recommendationId_fkey" FOREIGN KEY ("recommendationId") REFERENCES "Recommendation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Feedback" ADD CONSTRAINT "Feedback_notificationId_fkey" FOREIGN KEY ("notificationId") REFERENCES "Notification"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "LearningPreference" ADD CONSTRAINT "LearningPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LearningPreference" ADD CONSTRAINT "LearningPreference_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarToken" ADD CONSTRAINT "CalendarToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
